# Site Settings
title:               My Life Unlearned
tagline:             curiosity fuels education
description:
baseurl:            #""
url:                #"https://lenpaul.github.io"
github:
  url:               #"https://elisepotts.github.io"
author:
  name:              "Elise Marie Potts"
  email:             "elise.potts@gmail.com"
  twitter:           "elisempotts"
  instagram:         "elisemariepotts"
  github:            "elisepotts"
  linkedin:          "elisepotts"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Projects
  url: /projects

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
