# Site Settings
title:               My Life Unlearned
tagline:             this is a tagline
description:
baseurl:            #""
url:                #"https://lenpaul.github.io"
github:
  url:               #"http://elisepotts.github.io"
author:
  name:              "Elise Marie Potts"
  email:             "elise.potts@gmail.com"
  twitter:           "@elisempotts"
  github:            "@elisepotts"
  linkedin:          "Elise Potts"
navigation:
- title: About
  url: /about
- title: Writing
  url: /writing
- title: Contact
  url: /contact

paginate:            5
disqus:              #"your-disqus"

# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
gems:                [jekyll-paginate]
